### ISSUE TITLE
Wrong hostname on CSP docs

### ISSUE THREAD

**Issue by oschvr** [segmentio/segment-docs#2358]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/#using-a-strict-content-security-policy-on-the-page

### What part(s) of the article would you like to see updated?

The urls requested to be clear listed:

- https://cdn.segment.com/v1/projects/<WRITE_KEY>/settings
- https://cdn.segment.com/analytics-next/bundles/*
- https://cdn.segment.com/next-integrations/integrations/*

But it seems the actual hostname used is `cdn.segment.io`

**Comment by markzegarelli** [comment]
Hi @oschvr, thanks for reaching out! Segment serves Analytics.js from both domains (`cdn.segment.com` and `cdn.segment.io`). `cdn.segment.com` is a bit more modern with regards to caching and compression, so that is what we publish in the docs. That said, `cdn.segment.io` still functions, and you can use the provided instructions with that domain swapped in.

I'll leave this issue open for now, however if you encounter issues with your configuration, please contact Segment Support directly.
