### ISSUE TITLE
[Content]: Pendo Content Missing

### ISSUE THREAD

**Issue by k-griese** [segmentio/segment-docs#3236]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/pendo/

### What part(s) of the article would you like to see updated?

The Destination Information needs to be updated: Currently the doc mentioned Pendo accepts Identify and Group call however, further down on the page it mentions Track call as well. 

Also, the accepted connect modes look like Device only for web however, a cloud-mode option appears present further down in the document.

**Comment by markzegarelli** [comment]
Thanks @k-griese. We'll update the content of the doc to remove information pertaining to Track calls, as it appears that Pendo does not support this.

With regards to the mention of Cloud-mode, let me have a think about how best to reword this, as it is technically a Cloud-mode connection, but uses a webhook rather than the Pendo destination directly.
